name: Package Application

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  create-installers:
    name: Generate ${{ matrix.installer_type }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            installer_type: msi

          - os: macos-latest
            installer_type: dmg

          - os: ubuntu-latest
            installer_type: deb

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Executable JAR
        run: mvn clean package -DskipTests -Dspotless.check.skip

      - name: Prepare Linux Deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot binutils rpm

      - name: Run jpackage
        run: mvn panteleyev:jpackage -Dtype=${{ matrix.installer_type }}

      - name: Archive Installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.installer_type }}-Package
          path: target/dist/*